name: simple_controller
description: "A lightweight and efficient state management solution for Flutter applications."
version: 1.4.0
homepage: https://github.com/davidchow24/simple_controller

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.16.0"

dependencies:
  flutter:
    sdk: flutter
