name: simple_controller
description: "A wrapper around StatefulWidget to make them easier to use and more reusable."
version: 1.2.0
homepage: https://github.com/davidchow24/simple_controller

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.16.0"

dependencies:
  flutter:
    sdk: flutter
